export const radioStationsData = [
  {
    freq: "99.1",
    title: "Rádio Mais",
    src: "https://radios.justweb.pt/8050/stream/?1685627470876",
    country: "Angola",
    genre: "",
    image: "http://imgs.sapo.pt/radiosonlineao/content/img/radio_mais.jpg",
  },
  {
    freq: "99.9",
    title: "Rádio Luanda",
    src: "https://radios.vpn.sapo.pt/AO/radio11.mp3",
    country: "Angola",
    genre: "",
    image: "http://imgs.sapo.pt/radiosonlineao/content/img/radioluanda.jpg",
  },
  {
    freq: "91.0",
    title: "Radio Despertar",
    src: "http://radios.vpn.sapo.pt/AO/radio15.mp3",
    country: "Angola",
    genre: "Notícias",
    image:
      "http://imgs.sapo.pt/radiosonlineao/content/img/logo_despertarangola.jpg",
  },
  {
    freq: "97.9",
    title: "Rádio Romântica",
    src: "http://radios.vpn.sapo.pt/AO/radio4.mp3",
    country: "Angola",
    genre: "Musica",
    image: "http://imgs.sapo.pt/radiosonlineao/content/img/r_romantica.png",
  },
  {
    freq: "",
    title: "Rádio 94 FM",
    src: "https://www.ouviraradio.com/proxy.php?link=185.11.164.106&amp;porta=35022&amp;path=/stream?type=mp3",
    country: "Angola",
    genre: "",
    image: "https://www.ouviraradio.com/image/80/1681028235-186726133.png",
  },
  {
    freq: "98.4",
    title: "Rádio Kairós",
    src: "https://radios.vpn.sapo.pt/AO/radio9.mp3",
    country: "Angola",
    genre: "",
    image: "http://imgs.sapo.pt/radiosonlineao/content/img/kairos.jpg",
  },
  {
    freq: "",
    title: "FM STÉREO",
    src: "https://radios.vpn.sapo.pt/AO/radio7.mp3",
    country: "Angola",
    genre: "Músicas",
    image: "http://imgs.sapo.pt/radiosonlineao/content/img/fmstereo.jpg",
  },
  {
    freq: "97.3",
    title: "Rafio 5",
    src: "https://radios.vpn.sapo.pt/AO/radio5.mp3",
    country: "Angola",
    genre: "Músicas",
    image: "http://imgs.sapo.pt/radiosonlineao/content/img/radio_5.jpg",
  },
  {
    freq: "88.5",
    title: "Radio Escola",
    src: "https://radios.vpn.sapo.pt/AO/radio1.mp3",
    country: "UK",
    genre: "Política",
    image: "http://imgs.sapo.pt/radiosonlineao/content/img/radio_escola.jpg",
  },
  {
    freq: "95.5 FM",
    title: "LAC",
    src: "https://radios.vpn.sapo.pt/AO/radio14.mp3",
    country: "Angola",
    genre: "",
    image: "http://imgs.sapo.pt/radiosonlineao/content/img/lac.jpg",
  },
  {
    freq: "102.1 FM",
    title: "Rádio Cazenga",
    src: "https://radios.vpn.sapo.pt/AO/radio13.mp3",
    country: "Angola",
    genre: "",
    image: "http://imgs.sapo.pt/radiosonlineao/content/img/cazenga.jpg",
  },
  {
    freq: "92.3",
    title: "Radio Unia",
    src: "https://radios.vpn.sapo.pt/AO/radio2.mp3",
    country: "Angola",
    genre: "",
    image: "http://imgs.sapo.pt/radiosonlineao/content/img/radio_unia.png",
  },
  {
    freq: "99.4",
    title: "Radio Viana",
    src: "https://radios.vpn.sapo.pt/AO/radio16.mp3",
    country: "Angola",
    genre: "",
    image: "http://imgs.sapo.pt/radiosonlineao/content/img/radio-viana.jpg",
  },
  {
    freq: "FM",
    title: "Radio Cacuaco",
    src: "https://radios.vpn.sapo.pt/AO/radio17.mp3",
    country: "Angola",
    genre: "",
    image: "http://imgs.sapo.pt/radiosonlineao/content/img/radio-cacuaco.jpg",
  },
  {
    freq: "FM",
    title: "Radio Sem Anestesia",
    src: "https://radios.vpn.sapo.pt/AO/radio19.mp3",
    country: "USA",
    genre: "Musica",
    image:
      "http://imgs.sapo.pt/radiosonlineao/content/img/radiosemanestesia.png",
  },
  {
    freq: "FM",
    title: "RDP Africa",
    src: "https://radios.vpn.sapo.pt/CV/radio12.mp3",
    country: "Angola",
    genre: "Informativo",
    image:
      "http://thumbs.sapo.pt/?pic=http%3A%2F%2Fimgs.sapo.pt%2Fradiosonlineao%2Fcontent%2Fimg%2Frdp_africa_2.jpg&W=100&H=75&crop=center",
  },
  {
    freq: "97.1",
    title: "RFI",
    src: "https://radios.vpn.sapo.pt/CV/radio8.mp3",
    country: "Portugal",
    genre: "",
    image:
      "http://thumbs.sapo.pt/?pic=http%3A%2F%2Fimgs.sapo.pt%2Fradiosonlineao%2Fcontent%2Fimg%2Flogo.png&W=100&H=75&crop=center&png=1",
  },
  {
    freq: "97.5 FM",
    title: "Radio Ecclesia",
    src: "https://mediaserv33.live-streams.nl:8089/stream",
    country: "Angola",
    genre: "",
    image: "http://imgs.sapo.pt/radiosonlineao/content/img/radio_ecclesia.jpg",
  },
  {
    freq: "FM",
    title: "Radio Kuia Bue",
    src: "https://mediaserv33.live-streams.nl:8089/stream",
    country: "Angola",
    genre: "Musica",
    image: "//cdn.onlineradiobox.com/img/l/1/47681.v10.png",
  },
  {
    freq: "99.1",
    title: "Rádio Mais",
    src: "https://radios.justweb.pt/8050/stream/?1685627470876",
    country: "Angola",
    genre: "Tendência",
    image:
      "https://thumbs.web.sapo.io/?W=800&H=800&png=1&delay_optim=1&png=1&epic=ZWY5T0CD6qqqvQBq25I+WUOQW+6a1IhI+WNfkzgjDYvyTOqtpoYDYcs3b24eiJtWuzunNl6MRWezHfGSjbII5leVIaBnZ3EBZVH5T90DQO6wPrk=",
  },
  {
    freq: "102.7",
    title: "Rádio PopHits",
    src: "http://stream.radiopop.com.br:9010/;",
    country: "Brazil",
    genre: "Tendência",
    image:
      "https://zeno.fm/_next/image/?url=https%3A%2F%2Fimages.zeno.fm%2FKY9wJc2rydT2vgOG7TiE0OrLYxjRLb8IfDgw7Q8N4pM%2Frs%3Afit%3A240%3A240%2Fg%3Ace%3A0%3A0%2FaHR0cHM6Ly9zdHJlYW0tdG9vbHMuemVub21lZGlhLmNvbS9jb250ZW50L3N0YXRpb25zLzJlZjE0ZmIwLTM3ZjYtNGNmYy04MjM4LWQ0ZmUwNDY4MWI2Ni9pbWFnZS8_dXBkYXRlZD0xNjc0NTQyNDM5MDAw.webp&w=1920&q=100",
  },
  {
    freq: "100.5",
    title: "Top Hits",
    src: "https://tophits.com/stream",
    country: "USA",
    genre: "Tendência",
    image: "https://i1.sndcdn.com/artworks-000543331965-wwjy31-t500x500.jpg",
  },
  {
    freq: "89.3",
    title: "NewsRadio",
    src: "https://newsradio.com/stream",
    country: "USA",
    genre: "Notícias",
    image:
      "https://usaradio.com/wp-content/uploads/2022/06/usa_radio_news_300x300.jpg",
  },
  {
    freq: "94.2",
    title: "News FM",
    src: "https://newsfm.net/stream",
    country: "UK",
    genre: "Notícias",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSi_RKbzjPipO29aB2P0UusBFA3coDxG3SGrQ&s",
  },
  {
    freq: "101.2",
    title: "SportsZone",
    src: "https://sportszone.com/stream",
    country: "USA",
    genre: "Desporto",
    image:
      "https://cfunity-affiliate-logos.nfhsnetwork.com/afla348ad8dc1_p659.png",
  },
  {
    freq: "88.9",
    title: "SportCity Radio",
    src: "https://sportcityradio.net/stream",
    country: "Australia",
    genre: "Desporto",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ--ZK6WAnGX0Xf1jVKBA4xx7zL6mkPxz0v9g&s",
  },
  {
    freq: "105.6",
    title: "MusicMania",
    src: "https://musicmania.com/stream",
    country: "Canada",
    genre: "Músicas",
    image: "",
  },
  {
    freq: "97.3",
    title: "MelodyMix FM",
    src: "https://melodymix.com/stream",
    country: "Germany",
    genre: "Músicas",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdfecJlBe6GG6MxRxdbA5CzrXQsYhlLemC-w&s",
  },
  {
    freq: "93.8",
    title: "PoliticsPulse",
    src: "https://politicspulse.net/stream",
    country: "UK",
    genre: "Política",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5MyTqVlGvLmJZ_X8ISjIGPw2ZQIygfUwZaQ&s",
  },
  {
    freq: "103.4",
    title: "PolicyPoint Radio",
    src: "https://policyradio.com/stream",
    country: "USA",
    genre: "Política",
    image: "",
  },
  {
    freq: "96.1",
    title: "EduTunes",
    src: "https://edutunes.com/stream",
    country: "Australia",
    genre: "Educação",
    image: "",
  },
  {
    freq: "90.7",
    title: "LearnRadio",
    src: "https://learnradio.net/stream",
    country: "Canada",
    genre: "Educação",
    image: "",
  },
  {
    freq: "99.4",
    title: "EntertainZone",
    src: "https://entertainzone.com/stream",
    country: "UK",
    genre: "Entretenimento",
    image: "",
  },
  {
    freq: "106.8",
    title: "FunTastic Radio",
    src: "https://funtasticradio.net/stream",
    country: "USA",
    genre: "Entretenimento",
    image: "",
  },
  {
    freq: "102.9",
    title: "BusinessBeats",
    src: "https://businessbeats.com/stream",
    country: "Australia",
    genre: "Negócios",
    image: "",
  },
  {
    freq: "91.5",
    title: "BizRadio",
    src: "https://bizradio.net/stream",
    country: "Canada",
    genre: "Negócios",
    image: "",
  },
  {
    freq: "97.1",
    title: "TalkTime",
    src: "https://talktime.com/stream",
    country: "UK",
    genre: "Conversas",
    image: "",
  },
  {
    freq: "104.3",
    title: "DiscussionRadio",
    src: "https://discussionradio.net/stream",
    country: "USA",
    genre: "Conversas",
    image: "",
  },
  {
    freq: "99.4",
    title: "Radio 5",
    src: "https://radios.vpn.sapo.pt/AO/radio5.mp3",
    country: "Angola",
    genre: "Tendência",
    image: "https://imgs.sapo.pt/radiosonlineao/content/img/radio_5.jpg",
  },
  {
    freq: "102.7",
    title: "Radio UNIA",
    src: "https://radios.vpn.sapo.pt/AO/radio2.mp3",
    country: "Angola",
    genre: "Tendência",
    image: "https://imgs.sapo.pt/radiosonlineao/content/img/radio_unia.png",
  },
  {
    freq: "100.5",
    title: "Radio Keirós",
    src: "https://radios.vpn.sapo.pt/AO/radio9.mp3",
    country: "Angola",
    genre: "Tendência",
    image: "https://imgs.sapo.pt/radiosonlineao/content/img/kairos.jpg",
  },
  {
    freq: "105.6",
    title: "Radio Escola",
    src: "https://radios.vpn.sapo.pt/AO/radio1.mp3",
    country: "Angola",
    genre: "Tendência",
    image: "https://imgs.sapo.pt/radiosonlineao/content/img/radio_escola.jpg",
  },
  {
    freq: "97.3",
    title: "Radio FM Stéreo",
    src: "https://radios.vpn.sapo.pt/AO/radio7.mp3",
    country: "Angola",
    genre: "Tendência",
    image: "https://imgs.sapo.pt/radiosonlineao/content/img/fmstereo.jpg",
  },
  {
    freq: "105.6",
    title: "Radio LAC",
    src: "https://radios.vpn.sapo.pt/AO/radio14.mp3",
    country: "Angola",
    genre: "Tendência",
    image: "https://imgs.sapo.pt/radiosonlineao/content/img/lac.jpg",
  },
  {
    freq: "105.6",
    title: "Joy FM",
    src: "http://stream.gbcghana.com/joyfm",
    country: "Gana",
    genre: "Tendência",
    image: "https://imgs.sapo.pt/radiosonlineao/content/img/lac.jpg",
  },
  {
    freq: "105.6",
    title: "Cool FM",
    src: "http://icy3.abacast.com/coolfm32",
    country: "Nigéria",
    genre: "Tendência",
    image: "https://imgs.sapo.pt/radiosonlineao/content/img/lac.jpg",
  },
  {
    freq: "105.6",
    title: "RAI Radio 1",
    src: "http://icestreaming.rai.it/1.mp3",
    country: "Itália",
    genre: "Tendência",
    image: "https://imgs.sapo.pt/radiosonlineao/content/img/lac.jpg",
  },
  {
    freq: "105.6",
    title: "Radio Nacional",
    src: "http://rne.rtveradio.cires21.com/rneradio.mp3",
    country: "Espanha",
    genre: "Notícias",
    image: "https://imgs.sapo.pt/radiosonlineao/content/img/lac.jpg",
  },
  {
    freq: "105.6",
    title: "Deutschlandfunk",
    src: "http://st01.dlf.de/dlf/01/128/mp3/stream.mp3",
    country: "Alemanha",
    genre: "Notícias",
    image: "https://imgs.sapo.pt/radiosonlineao/content/img/lac.jpg",
  },
  {
    freq: "105.6",
    title: "RTL",
    src: "http://streaming.radio.rtl.fr/rtl-1-44-128",
    country: "França",
    genre: "Diversos",
    image: "https://imgs.sapo.pt/radiosonlineao/content/img/lac.jpg",
  },
  {
    freq: "105.6",
    title: "CBC Radio One",
    src: "http://cbcmp3.ic.llnwd.net/stream/cbcmp3_cbc_r1_tor",
    country: "Canadá",
    genre: "Diversos",
    image: "https://imgs.sapo.pt/radiosonlineao/content/img/lac.jpg",
  },
  {
    freq: "105.6",
    title: "Radio Globo",
    src: "http://stream.radio.com:8000/radioglobo",
    country: "Brazil",
    genre: "Diversos",
    image: "https://imgs.sapo.pt/radiosonlineao/content/img/lac.jpg",
  },
];
