export const radioStationsData = [
  {
    freq: "99.1",
    title: "Rádio Mais",
    src: "https://radios.justweb.pt/8050/stream/?1685627470876",
    country: "Angola",
    genre: "",
    image: "http://imgs.sapo.pt/radiosonlineao/content/img/radio_mais.jpg",
  },
  {
    freq: "99.9",
    title: "Rádio Luanda",
    src: "https://radios.vpn.sapo.pt/AO/radio11.mp3",
    country: "Angola",
    genre: "",
    image: "http://imgs.sapo.pt/radiosonlineao/content/img/radioluanda.jpg",
  },
  {
    freq: "91.0",
    title: "Radio Despertar",
    src: "http://radios.vpn.sapo.pt/AO/radio15.mp3",
    country: "Angola",
    genre: "Notícias",
    image:
      "http://imgs.sapo.pt/radiosonlineao/content/img/logo_despertarangola.jpg",
  },
  {
    freq: "97.9",
    title: "Rádio Romântica",
    src: "http://radios.vpn.sapo.pt/AO/radio4.mp3",
    country: "Angola",
    genre: "Musica",
    image: "http://imgs.sapo.pt/radiosonlineao/content/img/r_romantica.png",
  },
  {
    freq: "",
    title: "Rádio 94 FM",
    src: "https://www.ouviraradio.com/proxy.php?link=185.11.164.106&amp;porta=35022&amp;path=/stream?type=mp3",
    country: "Angola",
    genre: "",
    image: "https://www.ouviraradio.com/image/80/1681028235-186726133.png",
  },
  {
    freq: "98.4",
    title: "Rádio Kairós",
    src: "https://radios.vpn.sapo.pt/AO/radio9.mp3",
    country: "Angola",
    genre: "",
    image: "http://imgs.sapo.pt/radiosonlineao/content/img/kairos.jpg",
  },
  {
    freq: "",
    title: "FM STÉREO",
    src: "https://radios.vpn.sapo.pt/AO/radio7.mp3",
    country: "Angola",
    genre: "Músicas",
    image: "http://imgs.sapo.pt/radiosonlineao/content/img/fmstereo.jpg",
  },
  {
    freq: "97.3",
    title: "Rafio 5",
    src: "https://radios.vpn.sapo.pt/AO/radio5.mp3",
    country: "Angola",
    genre: "Músicas",
    image: "http://imgs.sapo.pt/radiosonlineao/content/img/radio_5.jpg",
  },
  {
    freq: "88.5",
    title: "Radio Escola",
    src: "https://radios.vpn.sapo.pt/AO/radio1.mp3",
    country: "UK",
    genre: "Política",
    image: "http://imgs.sapo.pt/radiosonlineao/content/img/radio_escola.jpg",
  },
  {
    freq: "95.5 FM",
    title: "LAC",
    src: "https://radios.vpn.sapo.pt/AO/radio14.mp3",
    country: "Angola",
    genre: "",
    image: "http://imgs.sapo.pt/radiosonlineao/content/img/lac.jpg",
  },
  {
    freq: "102.1 FM",
    title: "Rádio Cazenga",
    src: "https://radios.vpn.sapo.pt/AO/radio13.mp3",
    country: "Angola",
    genre: "",
    image: "http://imgs.sapo.pt/radiosonlineao/content/img/cazenga.jpg",
  },
  {
    freq: "92.3",
    title: "Radio Unia",
    src: "https://radios.vpn.sapo.pt/AO/radio2.mp3",
    country: "Angola",
    genre: "",
    image: "http://imgs.sapo.pt/radiosonlineao/content/img/radio_unia.png",
  },
  {
    freq: "99.4",
    title: "Radio Viana",
    src: "https://radios.vpn.sapo.pt/AO/radio16.mp3",
    country: "Angola",
    genre: "",
    image: "http://imgs.sapo.pt/radiosonlineao/content/img/radio-viana.jpg",
  },
  {
    freq: "FM",
    title: "Radio Cacuaco",
    src: "https://radios.vpn.sapo.pt/AO/radio17.mp3",
    country: "Angola",
    genre: "",
    image: "http://imgs.sapo.pt/radiosonlineao/content/img/radio-cacuaco.jpg",
  },
  {
    freq: "FM",
    title: "Radio Sem Anestesia",
    src: "https://radios.vpn.sapo.pt/AO/radio19.mp3",
    country: "USA",
    genre: "Musica",
    image:
      "http://imgs.sapo.pt/radiosonlineao/content/img/radiosemanestesia.png",
  },
  {
    freq: "FM",
    title: "RDP Africa",
    src: "https://radios.vpn.sapo.pt/CV/radio12.mp3",
    country: "Angola",
    genre: "Informativo",
    image:
      "http://thumbs.sapo.pt/?pic=http%3A%2F%2Fimgs.sapo.pt%2Fradiosonlineao%2Fcontent%2Fimg%2Frdp_africa_2.jpg&W=100&H=75&crop=center",
  },
  {
    freq: "97.1",
    title: "RFI",
    src: "https://radios.vpn.sapo.pt/CV/radio8.mp3",
    country: "Portugal",
    genre: "",
    image:
      "http://thumbs.sapo.pt/?pic=http%3A%2F%2Fimgs.sapo.pt%2Fradiosonlineao%2Fcontent%2Fimg%2Flogo.png&W=100&H=75&crop=center&png=1",
  },
  {
    freq: "97.5 FM",
    title: "Radio Ecclesia",
    src: "https://mediaserv33.live-streams.nl:8089/stream",
    country: "Angola",
    genre: "",
    image: "http://imgs.sapo.pt/radiosonlineao/content/img/radio_ecclesia.jpg",
  },
  {
    freq: "FM",
    title: "Radio Kuia Bue",
    src: "https://mediaserv33.live-streams.nl:8089/stream",
    country: "Angola",
    genre: "Musica",
    image: "//cdn.onlineradiobox.com/img/l/1/47681.v10.png",
  },
];
